version: "3.8"
services:
  front:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    # command: --backends "http://web1:80,http://web2:80,http://web3:80"
    command: tail -f /dev/null
  web1:
    image: strm/helloworld-http
  web2:
    image: strm/helloworld-http
  web3:
    image: strm/helloworld-http
